/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SDC (https://sketchfab.com/3Duae)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/free-lamborghini-terzo-millennio-7ad3dffa9d344c3c978eafcc220cb709
title: ( FREE ) Lamborghini Terzo Millennio
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./asset2/scene.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.81}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.16, 0.29, -0.76]} scale={0.12}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={nodes.Object_4.material}
            />
          </group>
          <group
            position={[0.22, 0.36, -0.55]}
            rotation={[-Math.PI / 2, 1.57, 0]}
            scale={0.03}
          >
            <group rotation={[Math.PI / 2, 0, Math.PI / 2]}>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_8.geometry}
                  material={nodes.Object_8.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_10.geometry}
                  material={nodes.Object_10.material}
                />
              </group>
            </group>
          </group>
          <group
            name="top_wing_R_anim_8"
            position={[-0.22, 0.36, -0.55]}
            rotation={[-Math.PI / 2, 1.57, 0]}
            scale={0.03}
          >
            <group rotation={[Math.PI / 2, 0, Math.PI / 2]}>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_14.geometry}
                  material={nodes.Object_14.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_16.geometry}
                  material={nodes.Object_16.material}
                />
              </group>
            </group>
          </group>
          <group position={[0.19, 0.1, 0.32]} scale={0.12}>
            <mesh
              geometry={nodes.Object_18.geometry}
              material={nodes.Object_18.material}
            />
          </group>
          <group position={[-0.58, 0.11, 0.19]} scale={0.12}>
            <mesh
              geometry={nodes.Object_20.geometry}
              material={nodes.Object_20.material}
            />
            <mesh
              geometry={nodes.Object_21.geometry}
              material={nodes.Object_21.material}
            />
          </group>
          <group
            position={[0, 0, 0]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[0.03, 0.03, 0.03]}
          >
            <group position={[15.01, 5.39, -22.68]}>
              <group position={[-0.61, 0, 0]} scale={0.95}>
                <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_27.geometry}
                    material={nodes.Object_27.material}
                  />
                </group>
                <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_29.geometry}
                    material={nodes.Object_29.material}
                  />
                </group>
                <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_31.geometry}
                    material={nodes.Object_31.material}
                  />
                </group>
              </group>
              <group position={[-0.51, -0.02, -0.01]} scale={0.95}>
                <group position={[7.66, -0.6, -1.11]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_34.geometry}
                    material={nodes.Object_34.material}
                  />
                </group>
                <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_36.geometry}
                    material={nodes.Object_36.material}
                  />
                </group>
              </group>
              <group scale={0.95}>
                <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_39.geometry}
                    material={nodes.Object_39.material}
                  />
                </group>
              </group>
            </group>
            <group
              position={[-14.96, 5.39, -22.68]}
              rotation={[-Math.PI, 0, -Math.PI]}
            >
              <group position={[-0.61, 0, 0]} scale={0.95}>
                <group position={[7.71, -0.6, -1.1]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_44.geometry}
                    material={nodes.Object_44.material}
                  />
                </group>
                <group position={[7.72, -0.6, -1.11]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_46.geometry}
                    material={nodes.Object_46.material}
                  />
                </group>
                <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_48.geometry}
                    material={nodes.Object_48.material}
                  />
                </group>
              </group>
              <group position={[-0.51, -0.02, -0.01]} scale={0.95}>
                <group position={[7.7, -0.6, -1.11]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_51.geometry}
                    material={nodes.Object_51.material}
                  />
                </group>
                <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_53.geometry}
                    material={nodes.Object_53.material}
                  />
                </group>
              </group>
              <group scale={0.95}>
                <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_56.geometry}
                    material={nodes.Object_56.material}
                  />
                </group>
              </group>
            </group>
            <group position={[0.01, 11.99, 30.83]}>
              <group
                position={[-0.01, 0.03, 5.04]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              >
                <group
                  position={[-1.6, 0, -0.06]}
                  rotation={[Math.PI / 2, 0, Math.PI / 2]}
                >
                  <group
                    position={[7.71, -0.05, -1.11]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={[4.81, 4.81, 4.81]}
                  >
                    <mesh
                      geometry={nodes.Object_61.geometry}
                      material={nodes.Object_61.material}
                    />
                  </group>
                </group>
              </group>
              <group position={[-13.92, 0, 0]}>
                <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_64.geometry}
                    material={nodes.Object_64.material}
                  />
                </group>
              </group>
            </group>
            <group
              position={[0, 0.49, -36.87]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            >
              <group rotation={[Math.PI / 2, 0, Math.PI / 2]}>
                <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_68.geometry}
                    material={nodes.Object_68.material}
                  />
                </group>
                <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_70.geometry}
                    material={nodes.Object_70.material}
                  />
                </group>
              </group>
            </group>
            <group
              position={[0, 1.29, -35.25]}
              rotation={[0, 0.91, -Math.PI / 2]}
            >
              <group
                position={[2.07, 0, -0.14]}
                rotation={[0.91, 0, Math.PI / 2]}
              >
                <group position={[0.09, 2.02, -0.57]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_74.geometry}
                    material={nodes.Object_74.material}
                  />
                </group>
              </group>
            </group>
            <group position={[-5.3, 9.93, -11.28]} rotation={[-1.47, 0, 0]}>
              <group position={[-3.14, 10.6, 2.56]} rotation={[1.47, 0, 0]}>
                <group position={[3.14, -3.34, 10.77]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_78.geometry}
                    material={materials.Volant}
                  />
                </group>
                <group position={[3.14, -3.49, 11.41]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_80.geometry}
                    material={nodes.Object_80.material}
                  />
                </group>
              </group>
            </group>
            <group position={[-8.44, 8.47, -0.48]}>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_83.geometry}
                  material={nodes.Object_83.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_85.geometry}
                  material={nodes.Object_85.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_87.geometry}
                  material={nodes.Object_87.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_89.geometry}
                  material={nodes.Object_89.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_91.geometry}
                  material={nodes.Object_91.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_93.geometry}
                  material={nodes.Object_93.material}
                />
                <mesh
                  geometry={nodes.Object_94.geometry}
                  material={materials.Rouge}
                />
                <mesh
                  geometry={nodes.Object_95.geometry}
                  material={nodes.Object_95.material}
                />
                <mesh
                  geometry={nodes.Object_96.geometry}
                  material={nodes.Object_96.material}
                />
                <mesh
                  geometry={nodes.Object_97.geometry}
                  material={nodes.Object_97.material}
                />
                <mesh
                  geometry={nodes.Object_98.geometry}
                  material={materials.Sige}
                />
                <mesh
                  geometry={nodes.Object_99.geometry}
                  material={materials.Vert}
                />
                <mesh
                  geometry={nodes.Object_100.geometry}
                  material={materials.Blanc}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_102.geometry}
                  material={nodes.Object_102.material}
                />
                <mesh
                  geometry={nodes.Object_103.geometry}
                  material={materials.Material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_105.geometry}
                  material={materials["Material.002"]}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_107.geometry}
                  material={nodes.Object_107.material}
                />
              </group>
              <group position={[7.71, -0.6, -0.91]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_109.geometry}
                  material={nodes.Object_109.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_111.geometry}
                  material={nodes.Object_111.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_113.geometry}
                  material={nodes.Object_113.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_115.geometry}
                  material={nodes.Object_115.material}
                />
              </group>
            </group>
            <group position={[-13.32, 1.9, 29.61]}>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_118.geometry}
                  material={nodes.Object_118.material}
                />
              </group>
            </group>
            <group position={[-11.19, 9.07, -18.78]}>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_121.geometry}
                  material={nodes.Object_121.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_123.geometry}
                  material={nodes.Object_123.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_125.geometry}
                  material={nodes.Object_125.material}
                />
              </group>
            </group>
            <group position={[11.18, 9.07, -18.78]}>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_128.geometry}
                  material={nodes.Object_128.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_130.geometry}
                  material={nodes.Object_130.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_132.geometry}
                  material={nodes.Object_132.material}
                />
              </group>
            </group>
            <group position={[-16.65, 0.9, 18.11]}>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_135.geometry}
                  material={nodes.Object_135.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_137.geometry}
                  material={nodes.Object_137.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_139.geometry}
                  material={nodes.Object_139.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_141.geometry}
                  material={nodes.Object_141.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_143.geometry}
                  material={nodes.Object_143.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_145.geometry}
                  material={nodes.Object_145.material}
                />
              </group>
            </group>
            <group position={[16.65, 0.9, 18.11]}>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_148.geometry}
                  material={nodes.Object_148.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_150.geometry}
                  material={nodes.Object_150.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_152.geometry}
                  material={nodes.Object_152.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_154.geometry}
                  material={nodes.Object_154.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_156.geometry}
                  material={nodes.Object_156.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_158.geometry}
                  material={nodes.Object_158.material}
                />
              </group>
            </group>
            <group position={[-0.01, 15.69, 9.11]}>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_161.geometry}
                  material={nodes.Object_161.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_163.geometry}
                  material={nodes.Object_163.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_165.geometry}
                  material={nodes.Object_165.material}
                />
              </group>
            </group>
            <group position={[-10.29, 10.65, 34.02]}>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_168.geometry}
                  material={nodes.Object_168.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_170.geometry}
                  material={nodes.Object_170.material}
                />
              </group>
            </group>
            <group position={[0, 2.66, -33.69]}>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_173.geometry}
                  material={nodes.Object_173.material}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_175.geometry}
                  material={nodes.Object_175.material}
                />
              </group>
            </group>
            <group position={[0, 12.22, 3.48]}>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_178.geometry}
                  material={nodes.Object_178.material}
                />
                <mesh
                  geometry={nodes.Object_179.geometry}
                  material={nodes.Object_179.material}
                />
                <mesh
                  geometry={nodes.Object_180.geometry}
                  material={materials.Lumire_blanche}
                />
                <mesh
                  geometry={nodes.Object_181.geometry}
                  material={nodes.Object_181.material}
                />
              </group>
            </group>
            <group position={[0, 12.71, 5.84]}>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_184.geometry}
                  material={nodes.Object_184.material}
                />
              </group>
            </group>
            <group position={[14.44, 5.84, 22.53]}>
              <group position={[-0.87, 0, 0]} scale={0.95}>
                <group position={[11.01, -0.64, -1.2]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_189.geometry}
                    material={nodes.Object_189.material}
                  />
                </group>
                <group position={[11.01, -0.64, -1.2]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_191.geometry}
                    material={nodes.Object_191.material}
                  />
                </group>
                <group position={[11.01, -0.64, -1.2]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_193.geometry}
                    material={nodes.Object_193.material}
                  />
                </group>
              </group>
              <group position={[-0.72, -0.03, -0.01]} scale={0.95}>
                <group position={[10.9, -0.64, -1.2]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_196.geometry}
                    material={nodes.Object_196.material}
                  />
                </group>
                <group position={[11.01, -0.64, -1.2]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_198.geometry}
                    material={nodes.Object_198.material}
                  />
                </group>
              </group>
              <group scale={0.95}>
                <group position={[11.01, -0.64, -1.2]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_201.geometry}
                    material={nodes.Object_201.material}
                  />
                </group>
              </group>
            </group>
            <group
              position={[-14.58, 5.84, 22.53]}
              rotation={[-Math.PI, 0, -Math.PI]}
            >
              <group position={[-0.91, 0, 0]} scale={0.95}>
                <group position={[11.48, -0.64, -1.18]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_206.geometry}
                    material={nodes.Object_206.material}
                  />
                </group>
                <group position={[11.51, -0.64, -1.2]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_208.geometry}
                    material={nodes.Object_208.material}
                  />
                </group>
                <group position={[11.48, -0.64, -1.2]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_210.geometry}
                    material={nodes.Object_210.material}
                  />
                </group>
              </group>
              <group position={[-0.76, -0.03, -0.01]} scale={0.95}>
                <group position={[11.47, -0.64, -1.2]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_213.geometry}
                    material={nodes.Object_213.material}
                  />
                </group>
                <group position={[11.48, -0.64, -1.2]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_215.geometry}
                    material={nodes.Object_215.material}
                  />
                </group>
              </group>
              <group scale={0.95}>
                <group position={[11.48, -0.64, -1.2]} scale={4.81}>
                  <mesh
                    geometry={nodes.Object_218.geometry}
                    material={nodes.Object_218.material}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
