/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: lazercar (https://sketchfab.com/lazercar)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/volvo-s90-recharge-free-9462b07c10244fd4a28d86846dc9e3a9
title: Volvo S90 Recharge (Free)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
// import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./asset2/scene.gltf");

  /*useFrame((state) => {
    const t = state.clock.getElapsedTime();
    group.current.rotation.z = -0.2 - (1 + Math.sin(t / 1.5)) / 20;
    group.current.rotation.x = Math.cos(t / 4) / 8;
    group.current.rotation.y = Math.sin(t / 4) / 8;
    group.current.position.y = (1 + Math.sin(t / 1.5)) / 10;
  });*/

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.1}>
          <group
            position={[78.82, 37.96, 161.37]}
            rotation={[-2.11, 1.56, -0.42]}
            scale={19.59}
          >
            <mesh
              geometry={nodes.Brake_Disc_FL_chrome001_0.geometry}
              material={nodes.Brake_Disc_FL_chrome001_0.material}
            />
            <mesh
              geometry={nodes.Brake_Disc_FL_null002_0.geometry}
              material={nodes.Brake_Disc_FL_null002_0.material}
            />
            <mesh
              geometry={nodes.Brake_Disc_FL_disc001_0.geometry}
              material={nodes.Brake_Disc_FL_disc001_0.material}
            />
          </group>
          <group
            position={[-80.04, 37.96, 160.8]}
            rotation={[-1.03, -1.56, 2.72]}
            scale={[19.59, 19.59, 19.59]}
          >
            <mesh
              geometry={nodes.Brake_Disc_FR_chrome001_0.geometry}
              material={nodes.Brake_Disc_FR_chrome001_0.material}
            />
            <mesh
              geometry={nodes.Brake_Disc_FR_null002_0.geometry}
              material={nodes.Brake_Disc_FR_null002_0.material}
            />
            <mesh
              geometry={nodes.Brake_Disc_FR_disc001_0.geometry}
              material={nodes.Brake_Disc_FR_disc001_0.material}
            />
          </group>
          <group
            position={[80.67, 37.96, -132.71]}
            rotation={[-2.11, 1.56, -0.42]}
            scale={19.59}
          >
            <mesh
              geometry={nodes.Brake_Disc_RL_chrome001_0.geometry}
              material={nodes.Brake_Disc_RL_chrome001_0.material}
            />
            <mesh
              geometry={nodes.Brake_Disc_RL_null002_0.geometry}
              material={nodes.Brake_Disc_RL_null002_0.material}
            />
            <mesh
              geometry={nodes.Brake_Disc_RL_disc001_0.geometry}
              material={nodes.Brake_Disc_RL_disc001_0.material}
            />
          </group>
          <group
            position={[-80.04, 37.96, -133.77]}
            rotation={[-1.03, -1.56, 2.72]}
            scale={[19.59, 19.59, 19.59]}
          >
            <mesh
              geometry={nodes.Brake_Disc_RR_chrome001_0.geometry}
              material={nodes.Brake_Disc_RR_chrome001_0.material}
            />
            <mesh
              geometry={nodes.Brake_Disc_RR_null002_0.geometry}
              material={nodes.Brake_Disc_RR_null002_0.material}
            />
            <mesh
              geometry={nodes.Brake_Disc_RR_disc001_0.geometry}
              material={nodes.Brake_Disc_RR_disc001_0.material}
            />
          </group>
          <group
            position={[78.6, 41.96, 180.69]}
            rotation={[-0.26, Math.PI / 2, 0]}
            scale={[3.82, 3.24, 3.82]}
          >
            <mesh
              geometry={nodes.Caliper_FL_caliper_0.geometry}
              material={nodes.Caliper_FL_caliper_0.material}
            />
            <mesh
              geometry={nodes.Caliper_FL_Metal_Rough001_0.geometry}
              material={nodes.Caliper_FL_Metal_Rough001_0.material}
            />
            <mesh
              geometry={nodes.Caliper_FL_Plastic001_0.geometry}
              material={nodes.Caliper_FL_Plastic001_0.material}
            />
          </group>
          <group
            position={[-79.9, 41.96, 180.69]}
            rotation={[-0.26, -Math.PI / 2, 0]}
            scale={[-3.82, 3.24, 3.82]}
          >
            <mesh
              geometry={nodes.Caliper_FR_caliper_0.geometry}
              material={nodes.Caliper_FR_caliper_0.material}
            />
            <mesh
              geometry={nodes.Caliper_FR_Metal_Rough001_0.geometry}
              material={nodes.Caliper_FR_Metal_Rough001_0.material}
            />
            <mesh
              geometry={nodes.Caliper_FR_Plastic001_0.geometry}
              material={nodes.Caliper_FR_Plastic001_0.material}
            />
          </group>
          <group
            position={[78.6, 41.96, -113.55]}
            rotation={[-0.26, Math.PI / 2, 0]}
            scale={[3.82, 3.24, 3.82]}
          >
            <mesh
              geometry={nodes.Caliper_RL_caliper_0.geometry}
              material={nodes.Caliper_RL_caliper_0.material}
            />
            <mesh
              geometry={nodes.Caliper_RL_Metal_Rough001_0.geometry}
              material={nodes.Caliper_RL_Metal_Rough001_0.material}
            />
            <mesh
              geometry={nodes.Caliper_RL_Plastic001_0.geometry}
              material={nodes.Caliper_RL_Plastic001_0.material}
            />
          </group>
          <group
            position={[-79.9, 41.96, -113.55]}
            rotation={[-0.26, -Math.PI / 2, 0]}
            scale={[-3.82, 3.24, 3.82]}
          >
            <mesh
              geometry={nodes.Caliper_RR_caliper_0.geometry}
              material={nodes.Caliper_RR_caliper_0.material}
            />
            <mesh
              geometry={nodes.Caliper_RR_Metal_Rough001_0.geometry}
              material={nodes.Caliper_RR_Metal_Rough001_0.material}
            />
            <mesh
              geometry={nodes.Caliper_RR_Plastic001_0.geometry}
              material={nodes.Caliper_RR_Plastic001_0.material}
            />
          </group>
          <group
            position={[93.67, 38.06, 161.03]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={1.17}
          >
            <mesh
              geometry={nodes.Rim_Bolt_FL_Rims001_0.geometry}
              material={nodes.Rim_Bolt_FL_Rims001_0.material}
            />
          </group>
          <group
            position={[-93.04, 38.06, 161.14]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={[1.16, 1.16, 1.16]}
          >
            <mesh
              geometry={nodes.Rim_Bolt_FR_Rims001_0.geometry}
              material={nodes.Rim_Bolt_FR_Rims001_0.material}
            />
          </group>
          <group
            position={[93.64, 38.06, -133.05]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1.16, 1.16, 1.16]}
          >
            <mesh
              geometry={nodes.Rim_Bolt_RL_Rims001_0.geometry}
              material={nodes.Rim_Bolt_RL_Rims001_0.material}
            />
          </group>
          <group
            position={[-93.04, 38.06, -133.43]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={1.16}
          >
            <mesh
              geometry={nodes.Rim_Bolts_RR_Rims001_0.geometry}
              material={nodes.Rim_Bolts_RR_Rims001_0.material}
            />
          </group>
          <group
            position={[90.68, 38.18, 160.8]}
            rotation={[-Math.PI / 2, 0, 1.58]}
            scale={[29.37, 29.37, 29.37]}
          >
            <mesh
              geometry={nodes.Rim_Emblem_FL_Rims001_0.geometry}
              material={nodes.Rim_Emblem_FL_Rims001_0.material}
            />
          </group>
          <group
            position={[-90.15, 38.18, 161.37]}
            rotation={[-Math.PI / 2, 0, -1.56]}
            scale={[29.37, 29.37, 29.37]}
          >
            <mesh
              geometry={nodes.Rim_Emblem_FR_Rims001_0.geometry}
              material={nodes.Rim_Emblem_FR_Rims001_0.material}
            />
          </group>
          <group
            position={[90.71, 38.18, -133.27]}
            rotation={[-Math.PI / 2, 0, 1.58]}
            scale={[28.81, 28.81, 28.81]}
          >
            <mesh
              geometry={nodes.Rim_Emblem_RL_Rims001_0.geometry}
              material={nodes.Rim_Emblem_RL_Rims001_0.material}
            />
          </group>
          <group
            position={[-90.22, 38.18, -133.21]}
            rotation={[-Math.PI / 2, 0, -1.56]}
            scale={[29.37, 29.37, 29.37]}
          >
            <mesh
              geometry={nodes.Rim_Emblem_RR_Rims001_0.geometry}
              material={nodes.Rim_Emblem_RR_Rims001_0.material}
            />
          </group>
          <group
            position={[93.67, 38.06, 161.03]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[28.32, 28.32, 28.32]}
          >
            <mesh
              geometry={nodes.Rim_FL_Rims001_0.geometry}
              material={nodes.Rim_FL_Rims001_0.material}
            />
          </group>
          <group
            position={[-93.04, 38.06, 161.14]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={[27.82, 27.82, 27.82]}
          >
            <mesh
              geometry={nodes.Rim_FR_Rims001_0.geometry}
              material={nodes.Rim_FR_Rims001_0.material}
            />
          </group>
          <group
            position={[93.64, 38.06, -133.05]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[27.78, 27.78, 27.78]}
          >
            <mesh
              geometry={nodes.Rim_RL_Rims001_0.geometry}
              material={nodes.Rim_RL_Rims001_0.material}
            />
          </group>
          <group
            position={[-93.04, 38.06, -133.43]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={[27.7, 27.7, 27.7]}
          >
            <mesh
              geometry={nodes.Rim_RR_Rims001_0.geometry}
              material={nodes.Rim_RR_Rims001_0.material}
            />
          </group>
          <group
            position={[82.16, 38.06, 161.03]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={[7.78, 8.85, 8.85]}
          >
            <mesh
              geometry={nodes.Tire_FL_Tire001_0.geometry}
              material={nodes.Tire_FL_Tire001_0.material}
            />
          </group>
          <group
            position={[-81.81, 37.75, 161.11]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[7.78, 8.85, 8.85]}
          >
            <mesh
              geometry={nodes.Tire_FR_Tire001_0.geometry}
              material={nodes.Tire_FR_Tire001_0.material}
            />
          </group>
          <group
            position={[82.16, 37.75, -132.95]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={[7.78, 8.85, 8.85]}
          >
            <mesh
              geometry={nodes.Tire_RL_Tire001_0.geometry}
              material={nodes.Tire_RL_Tire001_0.material}
            />
          </group>
          <group
            position={[-81.81, 37.75, -132.95]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[7.78, 8.85, 8.85]}
          >
            <mesh
              geometry={nodes.Tire_RR_Tire001_0.geometry}
              material={nodes.Tire_RR_Tire001_0.material}
            />
          </group>
          <group
            position={[80.39, 37.98, 161.31]}
            rotation={[2.14, 0, 1.56]}
            scale={[19.93, 19.93, 19.93]}
          >
            <mesh
              geometry={nodes.Wheelhub_FL_metal_rough002_0.geometry}
              material={nodes.Wheelhub_FL_metal_rough002_0.material}
            />
            <mesh
              geometry={nodes.Wheelhub_FL_chrome001_0.geometry}
              material={nodes.Wheelhub_FL_chrome001_0.material}
            />
          </group>
          <group
            position={[-81.61, 37.98, 160.85]}
            rotation={[1, 0, -1.58]}
            scale={[19.93, 19.93, 19.93]}
          >
            <mesh
              geometry={nodes.Wheelhub_FR_metal_rough002_0.geometry}
              material={nodes.Wheelhub_FR_metal_rough002_0.material}
            />
            <mesh
              geometry={nodes.Wheelhub_FR_chrome001_0.geometry}
              material={nodes.Wheelhub_FR_chrome001_0.material}
            />
          </group>
          <group
            position={[82.24, 37.98, -132.76]}
            rotation={[2.14, 0, 1.56]}
            scale={[19.93, 19.93, 19.93]}
          >
            <mesh
              geometry={nodes.Wheelhub_RL_metal_rough002_0.geometry}
              material={nodes.Wheelhub_RL_metal_rough002_0.material}
            />
            <mesh
              geometry={nodes.Wheelhub_RL_chrome001_0.geometry}
              material={nodes.Wheelhub_RL_chrome001_0.material}
            />
          </group>
          <group
            position={[-81.61, 37.98, -133.72]}
            rotation={[1, 0, -1.58]}
            scale={[19.93, 19.93, 19.93]}
          >
            <mesh
              geometry={nodes.Wheelhub_RR_metal_rough002_0.geometry}
              material={nodes.Wheelhub_RR_metal_rough002_0.material}
            />
            <mesh
              geometry={nodes.Wheelhub_RR_chrome001_0.geometry}
              material={nodes.Wheelhub_RR_chrome001_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Body_Frame_Car_Paint_0.geometry}
              material={nodes.Body_Frame_Car_Paint_0.material}
            />
            <mesh
              geometry={nodes.Body_Frame_rubber_0.geometry}
              material={nodes.Body_Frame_rubber_0.material}
            />
            <mesh
              geometry={nodes.Body_Frame_Plastic_0.geometry}
              material={nodes.Body_Frame_Plastic_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Bumper_Front_Car_Paint_0.geometry}
              material={nodes.Bumper_Front_Car_Paint_0.material}
            />
            <mesh
              geometry={nodes.Bumper_Front_Plastic_0.geometry}
              material={nodes.Bumper_Front_Plastic_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Bumper_Rear_Car_Paint_0.geometry}
              material={nodes.Bumper_Rear_Car_Paint_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Door_Front_Car_Paint_0.geometry}
              material={nodes.Door_Front_Car_Paint_0.material}
            />
            <mesh
              geometry={nodes.Door_Front_Black_Glossy_0.geometry}
              material={nodes.Door_Front_Black_Glossy_0.material}
            />
            <mesh
              geometry={nodes.Door_Front_Chrome_0.geometry}
              material={nodes.Door_Front_Chrome_0.material}
            />
            <mesh
              geometry={nodes.Door_Front_rubber_0.geometry}
              material={nodes.Door_Front_rubber_0.material}
            />
            <mesh
              geometry={nodes.Door_Front_Plastic_0.geometry}
              material={nodes.Door_Front_Plastic_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Door_Front_Handle_Chrome_0.geometry}
              material={nodes.Door_Front_Handle_Chrome_0.material}
            />
            <mesh
              geometry={nodes.Door_Front_Handle_Car_Paint_0.geometry}
              material={nodes.Door_Front_Handle_Car_Paint_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Door_Rear_Car_Paint_0.geometry}
              material={nodes.Door_Rear_Car_Paint_0.material}
            />
            <mesh
              geometry={nodes.Door_Rear_Chrome_0.geometry}
              material={nodes.Door_Rear_Chrome_0.material}
            />
            <mesh
              geometry={nodes.Door_Rear_Black_Glossy_0.geometry}
              material={nodes.Door_Rear_Black_Glossy_0.material}
            />
            <mesh
              geometry={nodes.Door_Rear_rubber_0.geometry}
              material={nodes.Door_Rear_rubber_0.material}
            />
            <mesh
              geometry={nodes.Door_Rear_Plastic_0.geometry}
              material={nodes.Door_Rear_Plastic_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Door_Rear_Handle_Chrome_0.geometry}
              material={nodes.Door_Rear_Handle_Chrome_0.material}
            />
            <mesh
              geometry={nodes.Door_Rear_Handle_Car_Paint_0.geometry}
              material={nodes.Door_Rear_Handle_Car_Paint_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Fender_Front_Car_Paint_0.geometry}
              material={nodes.Fender_Front_Car_Paint_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Hood_Car_Paint_0.geometry}
              material={nodes.Hood_Car_Paint_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.QuarterPanel_Chrome_Chrome_0.geometry}
              material={nodes.QuarterPanel_Chrome_Chrome_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Trunk_Car_Paint_0.geometry}
              material={nodes.Trunk_Car_Paint_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[14.29, 14.29, 14.29]}>
            <mesh
              geometry={nodes.MIrror_Car_Paint_0.geometry}
              material={nodes.MIrror_Car_Paint_0.material}
            />
            <mesh
              geometry={nodes.MIrror_Black_Glossy_0.geometry}
              material={nodes.MIrror_Black_Glossy_0.material}
            />
            <mesh
              geometry={nodes.MIrror_Glass_0.geometry}
              material={nodes.MIrror_Glass_0.material}
            />
            <mesh
              geometry={nodes.MIrror_Plastic_0.geometry}
              material={nodes.MIrror_Plastic_0.material}
            />
            <mesh
              geometry={nodes.MIrror_Chrome_0.geometry}
              material={nodes.MIrror_Chrome_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[14.29, 14.29, 14.29]}>
            <mesh
              geometry={nodes.MIrrorTurnSignal_Glass_Glass_0.geometry}
              material={nodes.MIrrorTurnSignal_Glass_Glass_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[14.29, 14.29, 14.29]}>
            <mesh
              geometry={
                nodes.MirrorTurnsignal_Reflector_Metal_Turnsignal_0.geometry
              }
              material={materials.Metal_Turnsignal}
            />
          </group>
          <group
            position={[0.16, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.QuarterPanel_Rubber_rubber_0.geometry}
              material={nodes.QuarterPanel_Rubber_rubber_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.FrontDoorGlass__Glass_0.geometry}
              material={nodes.FrontDoorGlass__Glass_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.SunRoof_Glass_0.geometry}
              material={nodes.SunRoof_Glass_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Windsheild__Glass_0.geometry}
              material={nodes.Windsheild__Glass_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Windsheild_Rear__Glass_0.geometry}
              material={nodes.Windsheild_Rear__Glass_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.RearDoorGlass__Glass_0.geometry}
              material={nodes.RearDoorGlass__Glass_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Windsheild_Null_null_0.geometry}
              material={nodes.Windsheild_Null_null_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Windsheild_Rear_Null_null_0.geometry}
              material={nodes.Windsheild_Rear_Null_null_0.material}
            />
          </group>
          <group
            position={[0.13, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.QuarterpanelGlass_Glass_0.geometry}
              material={nodes.QuarterpanelGlass_Glass_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.QuarterPanelGlass_Null_null_0.geometry}
              material={nodes.QuarterPanelGlass_Null_null_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.SunRoofFrame_Metal_Black_Rough_0.geometry}
              material={nodes.SunRoofFrame_Metal_Black_Rough_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Plane027_DoorPanelRear_0.geometry}
              material={materials.DoorPanelRear}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Floor_Shell_0.geometry}
              material={nodes.Floor_Shell_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Plane057_DoorPanelFront_0.geometry}
              material={nodes.Plane057_DoorPanelFront_0.material}
            />
            <mesh
              geometry={nodes.Plane057_DoorPanelFront_0_1.geometry}
              material={nodes.Plane057_DoorPanelFront_0_1.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Shell_Shell_0.geometry}
              material={nodes.Shell_Shell_0.material}
            />
            <mesh
              geometry={nodes.Shell_Shell_0_1.geometry}
              material={nodes.Shell_Shell_0_1.material}
            />
          </group>
          <group
            position={[41.68, 50.73, 22.53]}
            scale={[118.66, 118.66, 118.66]}
          >
            <mesh
              geometry={nodes.Driver_Seat_Front_Seat_0.geometry}
              material={nodes.Driver_Seat_Front_Seat_0.material}
            />
            <mesh
              geometry={nodes.Driver_Seat_Front_Seat_0_1.geometry}
              material={nodes.Driver_Seat_Front_Seat_0_1.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Driver_Carpet_Shell_0.geometry}
              material={nodes.Driver_Carpet_Shell_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Rear_Carpet_Shell_0.geometry}
              material={nodes.Rear_Carpet_Shell_0.material}
            />
          </group>
          <group
            position={[0.63, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.PlasticTrim_Shell_0.geometry}
              material={nodes.PlasticTrim_Shell_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={9.9}>
            <mesh
              geometry={nodes.SeatBelts_Front_Shell_0.geometry}
              material={nodes.SeatBelts_Front_Shell_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Rear_Seats_Rear_Seats_0.geometry}
              material={nodes.Rear_Seats_Rear_Seats_0.material}
            />
            <mesh
              geometry={nodes.Rear_Seats_Rear_Seats_0_1.geometry}
              material={nodes.Rear_Seats_Rear_Seats_0_1.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.RearShelf_Shell_0.geometry}
              material={nodes.RearShelf_Shell_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.SeatBelts_Rear_Rear_Seats_0.geometry}
              material={nodes.SeatBelts_Rear_Rear_Seats_0.material}
            />
          </group>
          <group
            position={[3.05, 87.45, 28.99]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.CenterConsole_CenterConsole_0.geometry}
              material={nodes.CenterConsole_CenterConsole_0.material}
            />
          </group>
          <group
            position={[-39.92, 50.73, 22.17]}
            scale={[118.66, 118.66, 122.11]}
          >
            <mesh
              geometry={nodes.Passenger_Seat_Front_Seat_0.geometry}
              material={nodes.Passenger_Seat_Front_Seat_0.material}
            />
            <mesh
              geometry={nodes.Passenger_Seat_Front_Seat_0_1.geometry}
              material={nodes.Passenger_Seat_Front_Seat_0_1.material}
            />
          </group>
          <group
            position={[38.3, 85.16, 53.9]}
            rotation={[-1.29, 0, -3.13]}
            scale={[32.6, 32.6, 32.6]}
          >
            <mesh
              geometry={nodes.SteeringWheel_Emblem_Steeringwheel_0.geometry}
              material={nodes.SteeringWheel_Emblem_Steeringwheel_0.material}
            />
          </group>
          <group
            position={[11.14, 63.91, 6.75]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Dashboard_Dashboard_0.geometry}
              material={nodes.Dashboard_Dashboard_0.material}
            />
            <mesh
              geometry={nodes.Dashboard_Dashboard_0_1.geometry}
              material={nodes.Dashboard_Dashboard_0_1.material}
            />
          </group>
          <group
            position={[38.57, 86.49, 54.11]}
            rotation={[-1.29, 0, -Math.PI]}
            scale={[17.95, 22.14, 17.95]}
          >
            <mesh
              geometry={nodes.SteeringWheel_Steeringwheel_0.geometry}
              material={nodes.SteeringWheel_Steeringwheel_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.PassengerCarpet_Shell_0.geometry}
              material={nodes.PassengerCarpet_Shell_0.material}
            />
          </group>
          <group
            position={[5.07, 62.15, 55.37]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[147.5, 135.16, 135.16]}
          >
            <mesh
              geometry={nodes.Shifterknob_CenterConsole_0.geometry}
              material={nodes.Shifterknob_CenterConsole_0.material}
            />
          </group>
          <group
            position={[5.07, 62.15, 55.37]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[109.13, 100, 100]}
          >
            <mesh
              geometry={nodes.Shifterknob_Crystal_crystal_0.geometry}
              material={materials.crystal}
            />
          </group>
          <group
            position={[3.05, 87.45, 28.99]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane049_CenterConsole_0.geometry}
              material={nodes.Plane049_CenterConsole_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.RearviewMirrorHolder_Shell_0.geometry}
              material={nodes.RearviewMirrorHolder_Shell_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.CeilingConsole__Shell_0.geometry}
              material={nodes.CeilingConsole__Shell_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.RearviewMirror_Shell_0.geometry}
              material={nodes.RearviewMirror_Shell_0.material}
            />
          </group>
          <group
            position={[38.57, 86.49, 54.11]}
            rotation={[-1.29, 0, -Math.PI]}
            scale={[17.95, 22.14, 17.95]}
          >
            <mesh
              geometry={nodes.SteeringColumn__Steeringwheel_0.geometry}
              material={nodes.SteeringColumn__Steeringwheel_0.material}
            />
          </group>
          <group
            position={[38.62, 85.71, 58.18]}
            rotation={[-2.3, 0, 0]}
            scale={[26.25, 26.25, 26.25]}
          >
            <mesh
              geometry={nodes.Stalks__Steeringwheel_0.geometry}
              material={nodes.Stalks__Steeringwheel_0.material}
            />
          </group>
          <group
            position={[19.33, 88.04, 74.46]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.18, 1.18, 1.18]}
          >
            <mesh
              geometry={nodes.Vents_Dashboard_0.geometry}
              material={nodes.Vents_Dashboard_0.material}
            />
          </group>
          <group
            position={[11.06, 63.91, 7.23]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.SpeedoGlass_Glass_0.geometry}
              material={nodes.SpeedoGlass_Glass_0.material}
            />
          </group>
          <group
            position={[11.14, 63.91, 6.63]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.SpeedoScreen_Speedometer_0.geometry}
              material={materials.Speedometer}
            />
          </group>
          <group
            position={[26.72, 47.3, 96.67]}
            rotation={[-2.46, 0, 0]}
            scale={[4.02, 4.02, 0.39]}
          >
            <mesh
              geometry={nodes.GasBrake_Pedal_Plastic_0.geometry}
              material={nodes.GasBrake_Pedal_Plastic_0.material}
            />
          </group>
          <group
            position={[11.14, 63.91, 6.75]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.InfoTainment_Screen_infotainmentScreen_0.geometry}
              material={materials.infotainmentScreen}
            />
          </group>
          <group
            position={[-67.64, 90.49, 72.31]}
            rotation={[-2.79, -0.06, -0.06]}
            scale={[0.68, 0.68, 0.68]}
          >
            <mesh
              geometry={nodes.Knobs_Dashboard_0.geometry}
              material={nodes.Knobs_Dashboard_0.material}
            />
          </group>
          <group
            position={[11.14, 63.91, 6.75]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Glovebox_Handle_Dashboard_0.geometry}
              material={nodes.Glovebox_Handle_Dashboard_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Chrome_Frame_Taillight__Taillight_0.geometry}
              material={nodes.Chrome_Frame_Taillight__Taillight_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Chrome_Frame_TrunkTaillight_Taillight_0.geometry}
              material={nodes.Chrome_Frame_TrunkTaillight_Taillight_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={
                nodes["Diffuser_3_Taillight_Turn_signal(taillight)_0"].geometry
              }
              material={
                nodes["Diffuser_3_Taillight_Turn_signal(taillight)_0"].material
              }
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={
                nodes.Diffuser_TrunkTaillight_Translucent_Glass_0.geometry
              }
              material={materials.Translucent_Glass}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={
                nodes.Diffusers_Taillight_Translucent_Glass001_0.geometry
              }
              material={materials["Translucent_Glass.001"]}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Frame_2_Taillight_Taillight_0.geometry}
              material={nodes.Frame_2_Taillight_Taillight_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Frame_2_Trunktaillight_Taillight_0.geometry}
              material={nodes.Frame_2_Trunktaillight_Taillight_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Frame_ReverseLight_Taillight_0.geometry}
              material={nodes.Frame_ReverseLight_Taillight_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Frame_Taillight_Taillight_0.geometry}
              material={nodes.Frame_Taillight_Taillight_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Frame_TrunkTaillight__Taillight_0.geometry}
              material={nodes.Frame_TrunkTaillight__Taillight_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.MainReflectors_Taillight_emission_0.geometry}
              material={nodes.MainReflectors_Taillight_emission_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Reflector_2_Taillight_Taillight_0.geometry}
              material={nodes.Reflector_2_Taillight_Taillight_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Reflector_2_Trunktaillight_Taillight_0.geometry}
              material={nodes.Reflector_2_Trunktaillight_Taillight_0.material}
            />
          </group>
          <group
            position={[-0.06, 0.01, 0.07]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Reflector_3_Taillight_Taillight_0.geometry}
              material={nodes.Reflector_3_Taillight_Taillight_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Reflector_Cubes_Taillight_Taillight_0.geometry}
              material={nodes.Reflector_Cubes_Taillight_Taillight_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Reflector_ReverseLight_Taillight_0.geometry}
              material={nodes.Reflector_ReverseLight_Taillight_0.material}
            />
          </group>
          <group
            position={[0, 0, -0.67]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Reflector_TrunkTaillight_emission_0.geometry}
              material={nodes.Reflector_TrunkTaillight_emission_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Taillight_glass_Glass_0.geometry}
              material={nodes.Taillight_glass_Glass_0.material}
            />
            <mesh
              geometry={nodes.Taillight_glass_Glass_Taillight_0.geometry}
              material={materials.Glass_Taillight}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Diffuser_ReverseLight_Glass_wavey_0.geometry}
              material={materials.Glass_wavey}
            />
          </group>
          <group
            position={[46.43, 91.43, -230.82]}
            rotation={[0, -0.27, 0]}
            scale={[0.24, 0.24, 0.24]}
          >
            <mesh
              geometry={nodes.Lightbulb_TrunkTaillight_Taillight_0.geometry}
              material={nodes.Lightbulb_TrunkTaillight_Taillight_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={
                nodes["Side_Diffuser_Taillight__Turn_signal(taillight)_0"]
                  .geometry
              }
              material={
                nodes["Side_Diffuser_Taillight__Turn_signal(taillight)_0"]
                  .material
              }
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[26.06, 26.06, 26.06]}>
            <mesh
              geometry={
                nodes.Chrome_trim_Headlight_Headlight_Insides_0.geometry
              }
              material={
                nodes.Chrome_trim_Headlight_Headlight_Insides_0.material
              }
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[26.06, 26.06, 26.06]}>
            <mesh
              geometry={nodes.Emitters_Headlight_Headlight_Insides_0.geometry}
              material={nodes.Emitters_Headlight_Headlight_Insides_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[26.06, 26.06, 26.06]}>
            <mesh
              geometry={nodes.Glass_Headlight_Glass_headlights_0.geometry}
              material={nodes.Glass_Headlight_Glass_headlights_0.material}
            />
            <mesh
              geometry={nodes.Glass_Headlight_Black_Glass_0.geometry}
              material={nodes.Glass_Headlight_Black_Glass_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[26.06, 26.06, 26.06]}>
            <mesh
              geometry={nodes.Glass_Runninglight_Glass_headlights_0.geometry}
              material={nodes.Glass_Runninglight_Glass_headlights_0.material}
            />
            <mesh
              geometry={nodes.Glass_Runninglight_GlassRunninglight_0.geometry}
              material={materials.GlassRunninglight}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[26.06, 26.06, 26.06]}>
            <mesh
              geometry={nodes.Misc_Headlight_Headlight_Insides_0.geometry}
              material={nodes.Misc_Headlight_Headlight_Insides_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[26.06, 26.06, 26.06]}>
            <mesh
              geometry={
                nodes.Plastic_bits_1_headlight_Headlight_Insides_0.geometry
              }
              material={
                nodes.Plastic_bits_1_headlight_Headlight_Insides_0.material
              }
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[26.06, 26.06, 26.06]}>
            <mesh
              geometry={
                nodes.Plastic_bits_2_Headlight_Headlight_Insides_0.geometry
              }
              material={
                nodes.Plastic_bits_2_Headlight_Headlight_Insides_0.material
              }
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[26.06, 26.06, 26.06]}>
            <mesh
              geometry={
                nodes.Reflector_Headlight_1_Headlight_Insides_0.geometry
              }
              material={
                nodes.Reflector_Headlight_1_Headlight_Insides_0.material
              }
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[26.06, 26.06, 26.06]}>
            <mesh
              geometry={
                nodes.Reflector_Headlight_2_Headlight_Insides_0.geometry
              }
              material={
                nodes.Reflector_Headlight_2_Headlight_Insides_0.material
              }
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[26.06, 26.06, 26.06]}>
            <mesh
              geometry={nodes.Reflector_Highbeam_Headlight_Insides_0.geometry}
              material={nodes.Reflector_Highbeam_Headlight_Insides_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[26.06, 26.06, 26.06]}>
            <mesh
              geometry={
                nodes.Reflector_Runninglight_Headlight_Insides_0.geometry
              }
              material={
                nodes.Reflector_Runninglight_Headlight_Insides_0.material
              }
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[26.06, 26.06, 26.06]}>
            <mesh
              geometry={nodes.Reflector_Turnsignal_Metal_Rough_0.geometry}
              material={nodes.Reflector_Turnsignal_Metal_Rough_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[26.06, 26.06, 26.06]}>
            <mesh
              geometry={nodes.Shell_Headlight_Headlight_Insides_0.geometry}
              material={nodes.Shell_Headlight_Headlight_Insides_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[26.06, 26.06, 26.06]}>
            <mesh
              geometry={nodes.Glass_Turnsignal_turnsignal_0.geometry}
              material={materials.turnsignal}
            />
            <mesh
              geometry={nodes.Glass_Turnsignal_heaxagon_glass_0.geometry}
              material={materials.heaxagon_glass}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[26.06, 26.06, 26.06]}>
            <mesh
              geometry={nodes.Logo_Headlight_Headlight_Insides_0.geometry}
              material={nodes.Logo_Headlight_Headlight_Insides_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Underbody_Plastic_0.geometry}
              material={nodes.Underbody_Plastic_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Exhaust_System_Black_Glossy_0.geometry}
              material={nodes.Exhaust_System_Black_Glossy_0.material}
            />
            <mesh
              geometry={nodes.Exhaust_System_tailpipes_0.geometry}
              material={materials.tailpipes}
            />
            <mesh
              geometry={nodes.Exhaust_System_null_0.geometry}
              material={nodes.Exhaust_System_null_0.material}
            />
          </group>
          <group
            position={[-0.09, 90.79, -239.21]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[355.11, 355.11, 317.34]}
          >
            <mesh
              geometry={nodes.Lettering_Rear_Chrome_0.geometry}
              material={nodes.Lettering_Rear_Chrome_0.material}
            />
          </group>
          <group
            position={[49.08, 83.22, -232.56]}
            rotation={[-1.59, 0.03, 2.93]}
            scale={[3.32, 3.32, 3.57]}
          >
            <mesh
              geometry={nodes.Lettering_Rear_2_Chrome_0.geometry}
              material={nodes.Lettering_Rear_2_Chrome_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.LeafCatcher_Plastic_0.geometry}
              material={nodes.LeafCatcher_Plastic_0.material}
            />
          </group>
          <group
            position={[9.6, 104.71, 114.62]}
            rotation={[-1.07, 0.02, 0.02]}
            scale={[86.41, 99.99, 100]}
          >
            <mesh
              geometry={nodes.WindsheildWiper_Left_Metal_Black_Rough_0.geometry}
              material={nodes.WindsheildWiper_Left_Metal_Black_Rough_0.material}
            />
          </group>
          <group
            position={[-43.84, 105.43, 107.75]}
            rotation={[-1.09, -0.12, -0.25]}
            scale={[94.79, 94.79, 94.79]}
          >
            <mesh
              geometry={
                nodes.WindsheildWiper_Right_Metal_Black_Rough_0.geometry
              }
              material={
                nodes.WindsheildWiper_Right_Metal_Black_Rough_0.material
              }
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Windsheild_Trim_Car_Paint_0.geometry}
              material={nodes.Windsheild_Trim_Car_Paint_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Null_null_0.geometry}
              material={nodes.Null_null_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.LowerGrille_Plastic_0.geometry}
              material={nodes.LowerGrille_Plastic_0.material}
            />
          </group>
          <group
            position={[0, 0, 249.58]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Emblem_Front_Black_Glass_0.geometry}
              material={nodes.Emblem_Front_Black_Glass_0.material}
            />
            <mesh
              geometry={nodes.Emblem_Front_Chrome_0.geometry}
              material={nodes.Emblem_Front_Chrome_0.material}
            />
            <mesh
              geometry={nodes.Emblem_Front_Black_Glossy_0.geometry}
              material={nodes.Emblem_Front_Black_Glossy_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Grille_Chrome_0.geometry}
              material={nodes.Grille_Chrome_0.material}
            />
            <mesh
              geometry={nodes.Grille_Black_Glossy_0.geometry}
              material={nodes.Grille_Black_Glossy_0.material}
            />
          </group>
          <group position={[-5.36, 61.46, 247.83]} scale={[3.46, 3.46, 3.46]}>
            <mesh
              geometry={nodes.Emblem_Grille_Plastic_0.geometry}
              material={nodes.Emblem_Grille_Plastic_0.material}
            />
          </group>
          <group
            position={[0, 0, 249.58]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.FrontCamera_Black_Glossy_0.geometry}
              material={nodes.FrontCamera_Black_Glossy_0.material}
            />
            <mesh
              geometry={nodes.FrontCamera_Plastic_0.geometry}
              material={nodes.FrontCamera_Plastic_0.material}
            />
            <mesh
              geometry={nodes.FrontCamera_Glass_0.geometry}
              material={nodes.FrontCamera_Glass_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Foglight_Glass_Glass_headlights_0.geometry}
              material={nodes.Foglight_Glass_Glass_headlights_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Foglight_Reflector_Chrome_0.geometry}
              material={nodes.Foglight_Reflector_Chrome_0.material}
            />
            <mesh
              geometry={nodes.Foglight_Reflector_Metal_Rough_0.geometry}
              material={nodes.Foglight_Reflector_Metal_Rough_0.material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Foglight_Shell_Plastic_0.geometry}
              material={nodes.Foglight_Shell_Plastic_0.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./asset2/scene.gltf");
